### signup user hzzz
POST http://localhost:8009/api/signup
Content-Type: application/json

{
	"fullname": "Hzzz",
	"email": "hzzz@gmail.com",
	"workspace": "acme",
	"password": "123456"
}

### signup user alice
POST http://localhost:8009/api/signup
Content-Type: application/json

{
	"fullname": "Alice",
	"email": "alice@gmail.com",
	"workspace": "acme",
	"password": "123456"
}

### signup user bob
POST http://localhost:8009/api/signup
Content-Type: application/json

{
	"fullname": "Bob",
	"email": "bob@gmail.com",
	"workspace": "acme",
	"password": "123456"
}

### signin user
# @name signin
POST http://localhost:8009/api/signin
Content-Type: application/json

{
	"email": "hzzz@gmail.com",
	"password": "123456"
}

@token = {{signin.response.body.token}}
