### signin user
# @name signin
POST http://localhost:8009/api/signin
Content-Type: application/json

{
	"email": "hzzz@gmail.com",
	"password": "123456"
}

@token = {{signin.response.body.token}}

### chat create
POST http://localhost:8009/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"name": "acme1",
	"members": [1, 2, 3],
	"public": false
}

### chat list
GET http://localhost:8009/api/chats
Authorization: Bearer {{token}}

### chat update
PATCH http://localhost:8009/api/chats/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"name": "acme",
	"members": [1, 2, 3],
	"public": false
}

### chat delete
DELETE http://localhost:8009/api/chats/1
Authorization: Bearer {{token}}

### create a message
POST http://localhost:8009/api/chats/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"content": "Hello, Alice!",
	"files": []
}

### send a message
GET http://localhost:8009/api/chats/1/messages?limit=5&last_id=5
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"content": "Hello, Alice!"
}
